---
version: 2
models:
- name: "model_fgyhuj_Aggregate_1"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy__temp_source"
  database: "database"
  schema: "default"
  config:
    enabled: true
  tables:
  - name: "prophecy__temp_fgyhuj_post_Aggregate_1"
    tags:
    - "prophecy_temp"
