---
version: 2
sources:
- name: "hive_metastore.arun123"
  database: "hive_metastore"
  schema: "arun123"
  tables:
  - name: "model"
    columns:
    - name: "customer_id"
      dataType:
        type: "Bigint"
    - name: "first_name"
      dataType:
        type: "String"
    - name: "last_name"
      dataType:
        type: "String"
    - name: "phone"
      dataType:
        type: "String"
    - name: "email"
      dataType:
        type: "String"
    - name: "country_code"
      dataType:
        type: "String"
    - name: "account_open_date"
      dataType:
        type: "Date"
    - name: "account_flags"
      dataType:
        type: "String"
  - name: "model1"
    columns:
    - name: "customer_id"
      dataType:
        type: "Bigint"
    - name: "first_name"
      dataType:
        type: "String"
    - name: "last_name"
      dataType:
        type: "String"
    - name: "first_order"
      dataType:
        type: "Date"
    - name: "most_recent_order"
      dataType:
        type: "Date"
    - name: "number_of_orders"
      dataType:
        type: "Bigint"
    - name: "customer_lifetime_value"
      dataType:
        type: "Double"
  - name: "sqlmodel"
    columns:
    - name: "customer_id"
      dataType:
        type: "Bigint"
    - name: "first_name"
      dataType:
        type: "String"
    - name: "last_name"
      dataType:
        type: "String"
    - name: "first_order"
      dataType:
        type: "Date"
    - name: "most_recent_order"
      dataType:
        type: "Date"
    - name: "number_of_orders"
      dataType:
        type: "Bigint"
    - name: "customer_lifetime_value"
      dataType:
        type: "Double"
- name: "hive_metastore.bad_schema"
  database: "hive_metastore"
  schema: "bad_schema"
  tables:
  - name: "catalogsteett"
    columns:
    - name: "customer"
      dataType:
        type: "Struct"
        fields:
        - name: "id"
          dataType:
            type: "Bigint"
        - name: "name"
          dataType:
            type: "String"
    - name: "order"
      dataType:
        type: "Struct"
        fields:
        - name: "amount"
          dataType:
            type: "Bigint"
- name: "hive_metastore.asadas"
  database: "hive_metastore"
  schema: "asadas"
  tables:
  - name: "test5672"
    columns:
    - name: "country_code"
      dataType:
        type: "String"
    - name: "1"
      dataType:
        type: "Integer"
    - name: "scv"
      dataType:
        type: "String"
