---
version: 2
sources:
- name: "hive_metastore.arun123"
  database: "hive_metastore"
  schema: "arun123"
  tables:
  - name: "model"
    columns:
    - name: "customer_id"
      dataType:
        type: "Bigint"
    - name: "first_name"
      dataType:
        type: "String"
    - name: "last_name"
      dataType:
        type: "String"
    - name: "first_order"
      dataType:
        type: "Date"
    - name: "most_recent_order"
      dataType:
        type: "Date"
    - name: "number_of_orders"
      dataType:
        type: "Bigint"
    - name: "customer_lifetime_value"
      dataType:
        type: "Double"
  - name: "model1"
    columns:
    - name: "customer_id"
      dataType:
        type: "Bigint"
    - name: "first_name"
      dataType:
        type: "String"
    - name: "last_name"
      dataType:
        type: "String"
    - name: "first_order"
      dataType:
        type: "Date"
    - name: "most_recent_order"
      dataType:
        type: "Date"
    - name: "number_of_orders"
      dataType:
        type: "Bigint"
    - name: "customer_lifetime_value"
      dataType:
        type: "Double"
- name: "hive_metastore.bad_schema"
  database: "hive_metastore"
  schema: "bad_schema"
  tables:
  - name: "catalogsteett"
    columns:
    - name: "customer"
      dataType:
        type: "Struct"
        fields:
        - name: "id"
          dataType:
            type: "Bigint"
        - name: "name"
          dataType:
            type: "String"
    - name: "order"
      dataType:
        type: "Struct"
        fields:
        - name: "amount"
          dataType:
            type: "Bigint"
