---
version: 2
sources:
- name: "hive_metastore.arun123"
  database: "hive_metastore"
  schema: "arun123"
  tables:
  - name: "sqlmodel"
    columns:
    - name: "customer_id"
      dataType:
        type: "Bigint"
    - name: "first_name"
      dataType:
        type: "String"
    - name: "last_name"
      dataType:
        type: "String"
    - name: "first_order"
      dataType:
        type: "Date"
    - name: "most_recent_order"
      dataType:
        type: "Date"
    - name: "number_of_orders"
      dataType:
        type: "Bigint"
    - name: "customer_lifetime_value"
      dataType:
        type: "Double"
  - name: "model"
    columns:
    - name: "customer_id"
      dataType:
        type: "Bigint"
    - name: "first_name"
      dataType:
        type: "String"
    - name: "last_name"
      dataType:
        type: "String"
    - name: "first_order"
      dataType:
        type: "Date"
    - name: "most_recent_order"
      dataType:
        type: "Date"
    - name: "number_of_orders"
      dataType:
        type: "Bigint"
    - name: "customer_lifetime_value"
      dataType:
        type: "Double"
- name: "hive_metastore.bad_schema"
  database: "hive_metastore"
  schema: "bad_schema"
  tables: []
- name: "hive_metastore.asadas"
  database: "hive_metastore"
  schema: "arun123"
  tables:
  - name: "test5672"
    columns:
    - name: "name"
      dataType:
        type: "String"
    - name: "age"
      dataType:
        type: "String"
  - name: "newera"
    columns:
    - name: "customer_id"
      dataType:
        type: "Bigint"
    - name: "first_name"
      dataType:
        type: "String"
    - name: "last_name"
      dataType:
        type: "String"
    - name: "first_order"
      dataType:
        type: "Date"
    - name: "most_recent_order"
      dataType:
        type: "Date"
    - name: "number_of_orders"
      dataType:
        type: "Bigint"
    - name: "customer_lifetime_value"
      dataType:
        type: "Double"
- name: "hive_metastore.default_qa_schema"
  database: "hive_metastore"
  schema: "default_qa_schema"
  tables:
  - name: "env_uitesting_shared_mid_model_1"
    columns:
    - name: "c_tinyint"
      dataType:
        type: "TinyInt"
    - name: "c_smallint"
      dataType:
        type: "SmallInt"
    - name: "c_int"
      dataType:
        type: "Integer"
    - name: "c_bigint"
      dataType:
        type: "Bigint"
    - name: "c_float"
      dataType:
        type: "Float"
    - name: "c_double"
      dataType:
        type: "Double"
    - name: "c_string"
      dataType:
        type: "String"
    - name: "c_boolean"
      dataType:
        type: "Boolean"
    - name: "c_array"
      dataType:
        type: "Array"
        dataType:
          type: "String"
    - name: "c_struct"
      dataType:
        type: "Struct"
        fields:
        - name: "city"
          dataType:
            type: "String"
        - name: "state"
          dataType:
            type: "String"
        - name: "pin"
          dataType:
            type: "Bigint"
