---
version: 2
sources:
- name: "hive_metastore.arun123"
  database: "hive_metastore"
  schema: "arun123"
  tables:
  - name: "model"
    columns:
    - name: "customer_id"
      dataType:
        type: "Bigint"
    - name: "first_name"
      dataType:
        type: "String"
    - name: "last_name"
      dataType:
        type: "String"
    - name: "phone"
      dataType:
        type: "String"
    - name: "email"
      dataType:
        type: "String"
    - name: "country_code"
      dataType:
        type: "String"
    - name: "account_open_date"
      dataType:
        type: "Date"
    - name: "account_flags"
      dataType:
        type: "String"
  - name: "model1"
    columns:
    - name: "customer_id"
      dataType:
        type: "Bigint"
    - name: "first_name"
      dataType:
        type: "String"
    - name: "last_name"
      dataType:
        type: "String"
    - name: "first_order"
      dataType:
        type: "Date"
    - name: "most_recent_order"
      dataType:
        type: "Date"
    - name: "number_of_orders"
      dataType:
        type: "Bigint"
    - name: "customer_lifetime_value"
      dataType:
        type: "Double"
  - name: "sqlmodel"
    columns:
    - name: "customer_id"
      dataType:
        type: "Bigint"
    - name: "first_name"
      dataType:
        type: "String"
    - name: "last_name"
      dataType:
        type: "String"
    - name: "first_order"
      dataType:
        type: "Date"
    - name: "most_recent_order"
      dataType:
        type: "Date"
    - name: "number_of_orders"
      dataType:
        type: "Bigint"
    - name: "customer_lifetime_value"
      dataType:
        type: "Double"
- name: "hive_metastore.bad_schema"
  database: "hive_metastore"
  schema: "bad_schema"
  tables:
  - name: "catalogsteett"
    columns:
    - name: "Year"
      dataType:
        type: "String"
    - name: "Industry_aggregation_NZSIOC"
      dataType:
        type: "String"
    - name: "Industry_code_NZSIOC"
      dataType:
        type: "String"
    - name: "Industry_name_NZSIOC"
      dataType:
        type: "String"
    - name: "Units"
      dataType:
        type: "String"
    - name: "Variable_code"
      dataType:
        type: "String"
    - name: "Variable_name"
      dataType:
        type: "String"
    - name: "Variable_category"
      dataType:
        type: "String"
    - name: "Value"
      dataType:
        type: "String"
    - name: "Industry_code_ANZSIC06"
      dataType:
        type: "String"
  - name: "test_table"
    columns:
    - name: "customer"
      dataType:
        type: "Struct"
        fields:
        - name: "id"
          dataType:
            type: "Bigint"
        - name: "name"
          dataType:
            type: "String"
    - name: "order"
      dataType:
        type: "Struct"
        fields:
        - name: "amount"
          dataType:
            type: "Bigint"
- name: "hive_metastore.asadas"
  database: "hive_metastore"
  schema: "asadas"
  tables:
  - name: "test5672"
    columns:
    - name: "country_code"
      dataType:
        type: "String"
    - name: "1"
      dataType:
        type: "Integer"
    - name: "scv"
      dataType:
        type: "String"
- name: "hive_metastore.default_qa_schema"
  database: "hive_metastore"
  schema: "default_qa_schema"
  tables:
  - name: "env_uitesting_shared_mid_model_1"
    columns:
    - name: "c_tinyint"
      dataType:
        type: "TinyInt"
    - name: "c_smallint"
      dataType:
        type: "SmallInt"
    - name: "c_int"
      dataType:
        type: "Integer"
    - name: "c_bigint"
      dataType:
        type: "Bigint"
    - name: "c_float"
      dataType:
        type: "Float"
    - name: "c_double"
      dataType:
        type: "Double"
    - name: "c_string"
      dataType:
        type: "String"
    - name: "c_boolean"
      dataType:
        type: "Boolean"
    - name: "c_array"
      dataType:
        type: "Array"
        dataType:
          type: "String"
    - name: "c_struct"
      dataType:
        type: "Struct"
        fields:
        - name: "city"
          dataType:
            type: "String"
        - name: "state"
          dataType:
            type: "String"
        - name: "pin"
          dataType:
            type: "Bigint"
