---
version: 2
models:
- name: "model_jhbkn_WindowFunction_1"
  tags:
  - "prophecy_temp"
- name: "model_jhbkn_Union_1"
  tags:
  - "prophecy_temp"
- name: "model_jhbkn_Filter_1"
  tags:
  - "prophecy_temp"
- name: "model_jhbkn_Reformat_1"
  tags:
  - "prophecy_temp"
- name: "model_jhbkn_SQLStatement_1"
  tags:
  - "prophecy_temp"
- name: "model_jhbkn_Macro_1"
  tags:
  - "prophecy_temp"
sources:
- name: "prophecy__temp_source"
  database: "database"
  schema: "default"
  config:
    enabled: true
  tables:
  - name: "prophecy__temp_jhbkn_post_Filter_1"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_jhbkn_post_SQLStatement_1"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_jhbkn_post_Macro_1"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_jhbkn_post_Reformat_1"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_jhbkn_post_WindowFunction_1"
    tags:
    - "prophecy_temp"
  - name: "prophecy__temp_jhbkn_post_Union_1"
    tags:
    - "prophecy_temp"
